[phases.setup]
nixPkgs = [
  "python312",
  "chromium",
  "chromedriver",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "freetype",
  "gcc-unwrapped.lib",
  "gdk-pixbuf",
  "gtk3",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "pango",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libxshmfence",
  "xorg.libXtst",
]

[variables]
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
